using System;
using System.Collections.Generic;

namespace KeyPayV2.Sg.Enums
{
    public enum PayCategoryType
    {
        Standard,
        LeaveLoading,
        GenuineRedundancyLeavePayment,
        OpeningBalanceAllowances,
        EtpTypeRTaxable,
        EtpTypeRTaxFree,
        EtpTypeOTaxable,
        EtpTypeOTaxFree,
        EtpLumpSumD,
        MethodB2AdditionalPaymentsOpeningBalance,
        StatutorySickPay,
        StatutoryMaternityPay,
        StatutoryAdoptionPay,
        StatutoryPaternityPay,
        StatutorySharedParentalPay,
        ExtraPay,
        RedundancyPayRetirementAllowance,
        GenuineRedundancyLeaveLoading,
        HolidayPay,
        TerminationHolidayPay,
        AccLevy,
        AverageEarnings,
        TerminationAverageEarnings,
        RelevantDailyPay,
        TerminationRelevantDailyPay,
        TerminationPublicHolidayPay,
        KeepingInTouchDay,
        LumpSumGratuity,
        LumpSumNoticePay,
        LumpSumExGratiaPayment,
        LumpSumOther,
        CompensationForLossOfOffice,
        Pre93RetirementBenefits,
        Post93RetirementBenefits,
        RestDayEmployerRequested,
        RestDayEmployeeRequested,
        PublicHoliday,
        EtpSuperableTypeOTaxable,
        EtpSuperableTypeOTaxFree,
        EtpTypeOUnusedLeavePayment,
        StatutoryParentalBereavementPay,
        UKPensionDeathBenefit,
        JobKeeperStart,
        JobKeeperFinish,
        JobKeeperTopUp,
        RestDay
    }
}
